name: creds_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  requests: ^4.7.0
  shared_preferences: ^2.2.0
  floor: ^1.4.2
  sqflite: ^2.2.8+4
  http_certificate_pinning: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
